language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t yo1sggk1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yo1sggk1/react-test npm test

after_success:
  - docker build -t yo1sggk1/multi-client ./client
  - docker build -t yo1sggk1/multi-nginx ./nginx
  - docker build -t yo1sggk1/multi-server ./server
  - docker build -t yo1sggk1/multi-worker ./worker
#Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin

#Take those images and push them to docker hub
- docker push yo1sggk1/multi-client ./client
- docker push yo1sggk1/multi-nginx ./nginx
- docker push yo1sggk1/multi-server ./server
- docker push yo1sggk1/multi-worker ./worker